### ISSUE TITLE
How to best implement "natural" session extension

### ISSUE THREAD

**Issue by scipilot** [futureproofphp/radar-domain-session#1]
Hi Andrew,

I have implemented a Radar-base API, and used some of your ideas and blog articles for inspiration - thanks for those.

I've implemented session cookie handling how you suggested, but "snooping" for the login response, and setting the cookie in the Responder like in 

https://github.com/futureproofphp/radar-domain-session/blob/master/src/Application/Delivery/DefaultResponder.php#L44

This all works fine, but I came to realise this isn't how native sessions work, with respect to session extension, i.e. when a user is using the site/api the session cookie expiry gets continually shifted into the future, presumably by the same "expiry time" 30 mins.

Currently with the method above, the cookie is set once, and will expire 30mins after login and log them out (absolute session length). This is seen as a "bug" by most users, when they hit that moment while still doing stuff!

How do you propose the best way of doing session extension in Radar?

I guess, I'd have to install a cookie extender in all responders (or base class), which would have to detect and modify the cookie if and only if it already existed. In my API I have public and private resources and no anonymous sessions, so I don't want to extend a cookie that doesn't exist.

I'm sure I can figure out a mechanism with lots of ifs and thens, but wondered if you could think of something more elegant, as you are familiar with the Radar framework.

thanks.

Ps. sorry, this isn't really an "Issue" in your repo, but if I had used it wholesale, it would be :)

**Comment by andrewshell** [comment]
Thanks for the feedback. I'll have to do some experimenting.  My first question is what happens if we call `SetCookie::create('SESSION_ID')` multiple times. If subsequent times just overwrite the cookie then we can probably just assign an expiration date at that point and call it a day.  Each time it runs it would get reset with a new expiration date.

If that doesn't work (and it might not) there is [FigResponseCookies::modify](https://github.com/dflydev/dflydev-fig-cookies#modify-a-response-cookie) which shows changing the expiration date. I would just need to figure out the best way to determine when to set the response cookie and when to modify it.

Full disclosure, my current job is all Node.js so I haven't worked with Radar or this code for a while.

**Comment by andrewshell** [comment]
This appears to resolve your issue:
https://github.com/futureproofphp/radar-domain-session/blob/53382fe44644cf5386d8ffa05e188bbb71e3d824/src/Application/Delivery/DefaultResponder.php#L42-L49

`FigResponseCookies::set` appears to replace the existing cookie. So in our responder, we can always set the cookie with the current value and a new expiration time 30 minutes in the future.

**Comment by scipilot** [comment]
Thanks for taking the time to respond.

Yes I agree - the set() does replace and update the cookie. In my case though, I didn't want the `if instanceof Session` as I want to extend the session while accessing _any API noun_, after login.

Also I needed to handle not re-adding a cookie with the set(), after the user has logged out (DELETE Session), so it got a bit more complex. I wanted to do it all in middleware but there you don't have access to the response payload (which I was surprised at) so it's a bit difficult to sniff the state.

Anyway thanks for your help, I think I've got a working model now.
